-- =============================================================================
-- RAIZ3Y STORE — Admin Mobile App Shell / Phase 1
-- المرحلة الأولى:
-- 1) تأسيس store_settings / admin_permissions / admin_audit_logs
-- 2) تفعيل RLS مع دوال صلاحيات آمنة
-- 3) إنشاء مسار bootstrap آمن لتحويل الحساب الحالي إلى Super Admin
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- دالة عامة لتحديث updated_at
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := timezone('utc', now());
  RETURN NEW;
END;
$$;

-- -----------------------------------------------------------------------------
-- الجداول الأساسية للمرحلة الأولى
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.store_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  singleton_key boolean NOT NULL DEFAULT true,
  maintenance_mode boolean NOT NULL DEFAULT false,
  maintenance_message text NOT NULL DEFAULT 'الموقع قيد الصيانة والتحديث حالياً، وسنسعد بخدمتكم مجدداً في أقرب وقت ممكن.',
  usd_to_sdg_rate numeric(12, 2) NOT NULL DEFAULT 0 CHECK (usd_to_sdg_rate >= 0),
  updated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT store_settings_singleton_key_uniq UNIQUE (singleton_key),
  CONSTRAINT store_settings_singleton_key_check CHECK (singleton_key = true)
);

CREATE TABLE IF NOT EXISTS public.admin_permissions (
  profile_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  is_super_admin boolean NOT NULL DEFAULT false,
  can_manage_orders boolean NOT NULL DEFAULT false,
  can_manage_wallets boolean NOT NULL DEFAULT false,
  can_manage_products boolean NOT NULL DEFAULT false,
  can_manage_settings boolean NOT NULL DEFAULT false,
  can_manage_maintenance boolean NOT NULL DEFAULT false,
  can_manage_admins boolean NOT NULL DEFAULT false,
  can_manage_coupons boolean NOT NULL DEFAULT false,
  can_manage_gift_cards boolean NOT NULL DEFAULT false,
  can_view_audit_logs boolean NOT NULL DEFAULT false,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.admin_audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  action text NOT NULL,
  target_table text,
  target_id text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_admin_permissions_super_admin
  ON public.admin_permissions (is_super_admin)
  WHERE is_super_admin = true;

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_admin_id_created_at
  ON public.admin_audit_logs (admin_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_target
  ON public.admin_audit_logs (target_table, target_id);

DROP TRIGGER IF EXISTS trg_store_settings_set_updated_at ON public.store_settings;
CREATE TRIGGER trg_store_settings_set_updated_at
BEFORE UPDATE ON public.store_settings
FOR EACH ROW
EXECUTE FUNCTION public.set_row_updated_at();

DROP TRIGGER IF EXISTS trg_admin_permissions_set_updated_at ON public.admin_permissions;
CREATE TRIGGER trg_admin_permissions_set_updated_at
BEFORE UPDATE ON public.admin_permissions
FOR EACH ROW
EXECUTE FUNCTION public.set_row_updated_at();

-- -----------------------------------------------------------------------------
-- Seed أولي متوافق مع الإعدادات القديمة
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  v_initial_rate numeric := 0;
BEGIN
  IF to_regclass('public.settings') IS NOT NULL THEN
    SELECT COALESCE(
      (
        SELECT CASE
          WHEN value ~ '^[0-9]+(\.[0-9]+)?$' THEN value::numeric
          ELSE 0
        END
        FROM public.settings
        WHERE key = 'usd_to_sdg_rate'
        LIMIT 1
      ),
      0
    )
    INTO v_initial_rate;
  END IF;

  INSERT INTO public.store_settings (
    singleton_key,
    maintenance_mode,
    maintenance_message,
    usd_to_sdg_rate
  )
  SELECT
    true,
    false,
    'الموقع قيد الصيانة والتحديث حالياً، وسنسعد بخدمتكم مجدداً في أقرب وقت ممكن.',
    v_initial_rate
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.store_settings
  );
END;
$$;

-- -----------------------------------------------------------------------------
-- دوال الصلاحيات
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.admin_permissions ap
    WHERE ap.profile_id = auth.uid()
      AND ap.is_super_admin = true
  );
$$;

CREATE OR REPLACE FUNCTION public.has_admin_permission(permission_key text)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT COALESCE(
    (
      SELECT
        ap.is_super_admin OR
        CASE permission_key
          WHEN 'manage_orders' THEN ap.can_manage_orders
          WHEN 'manage_wallets' THEN ap.can_manage_wallets
          WHEN 'manage_products' THEN ap.can_manage_products
          WHEN 'manage_settings' THEN ap.can_manage_settings
          WHEN 'manage_maintenance' THEN ap.can_manage_maintenance
          WHEN 'manage_admins' THEN ap.can_manage_admins
          WHEN 'manage_coupons' THEN ap.can_manage_coupons
          WHEN 'manage_gift_cards' THEN ap.can_manage_gift_cards
          WHEN 'view_audit_logs' THEN ap.can_view_audit_logs
          ELSE false
        END
      FROM public.admin_permissions ap
      WHERE ap.profile_id = auth.uid()
      LIMIT 1
    ),
    false
  );
$$;

-- تحديث دالة is_admin القديمة لتبقى متوافقة مع النظام الحالي
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.role = 'admin'
  )
  OR EXISTS (
    SELECT 1
    FROM public.admin_permissions ap
    WHERE ap.profile_id = auth.uid()
  );
$$;

CREATE OR REPLACE FUNCTION public.get_my_admin_context()
RETURNS jsonb
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'user_id', auth.uid(),
    'legacy_admin', EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role = 'admin'
    ),
    'is_admin', public.is_admin(),
    'is_super_admin', public.is_super_admin(),
    'permissions', COALESCE(
      (
        SELECT to_jsonb(ap) - 'created_by' - 'updated_by' - 'created_at' - 'updated_at'
        FROM public.admin_permissions ap
        WHERE ap.profile_id = auth.uid()
        LIMIT 1
      ),
      '{}'::jsonb
    )
  );
$$;

-- -----------------------------------------------------------------------------
-- دوال العمل الآمنة
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.append_admin_audit_log(
  p_action text,
  p_target_table text DEFAULT NULL,
  p_target_id text DEFAULT NULL,
  p_details jsonb DEFAULT '{}'::jsonb
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_log_id uuid;
  v_admin_id uuid := auth.uid();
BEGIN
  IF v_admin_id IS NULL THEN
    RAISE EXCEPTION 'AUTH_REQUIRED';
  END IF;

  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'ADMIN_REQUIRED';
  END IF;

  INSERT INTO public.admin_audit_logs (
    admin_id,
    action,
    target_table,
    target_id,
    details
  )
  VALUES (
    v_admin_id,
    trim(p_action),
    NULLIF(trim(COALESCE(p_target_table, '')), ''),
    NULLIF(trim(COALESCE(p_target_id, '')), ''),
    COALESCE(p_details, '{}'::jsonb)
  )
  RETURNING id INTO v_log_id;

  RETURN v_log_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_store_exchange_rate(p_rate numeric)
RETURNS public.store_settings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.store_settings;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'AUTH_REQUIRED';
  END IF;

  IF NOT public.has_admin_permission('manage_settings') THEN
    RAISE EXCEPTION 'MISSING_PERMISSION:manage_settings';
  END IF;

  IF p_rate IS NULL OR p_rate <= 0 THEN
    RAISE EXCEPTION 'INVALID_EXCHANGE_RATE';
  END IF;

  UPDATE public.store_settings
  SET usd_to_sdg_rate = p_rate,
      updated_by = auth.uid()
  WHERE singleton_key = true
  RETURNING * INTO v_row;

  PERFORM public.append_admin_audit_log(
    'set_store_exchange_rate',
    'store_settings',
    v_row.id::text,
    jsonb_build_object('usd_to_sdg_rate', p_rate)
  );

  RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_store_maintenance(
  p_enabled boolean,
  p_message text DEFAULT NULL
)
RETURNS public.store_settings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.store_settings;
  v_message text := COALESCE(
    NULLIF(trim(p_message), ''),
    'الموقع قيد الصيانة والتحديث حالياً، وسنسعد بخدمتكم مجدداً في أقرب وقت ممكن.'
  );
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'AUTH_REQUIRED';
  END IF;

  IF NOT public.has_admin_permission('manage_maintenance') THEN
    RAISE EXCEPTION 'MISSING_PERMISSION:manage_maintenance';
  END IF;

  UPDATE public.store_settings
  SET maintenance_mode = COALESCE(p_enabled, false),
      maintenance_message = v_message,
      updated_by = auth.uid()
  WHERE singleton_key = true
  RETURNING * INTO v_row;

  PERFORM public.append_admin_audit_log(
    'set_store_maintenance',
    'store_settings',
    v_row.id::text,
    jsonb_build_object(
      'maintenance_mode', COALESCE(p_enabled, false),
      'maintenance_message', v_message
    )
  );

  RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.upsert_admin_permissions(
  p_profile_id uuid,
  p_is_super_admin boolean DEFAULT false,
  p_can_manage_orders boolean DEFAULT false,
  p_can_manage_wallets boolean DEFAULT false,
  p_can_manage_products boolean DEFAULT false,
  p_can_manage_settings boolean DEFAULT false,
  p_can_manage_maintenance boolean DEFAULT false,
  p_can_manage_admins boolean DEFAULT false,
  p_can_manage_coupons boolean DEFAULT false,
  p_can_manage_gift_cards boolean DEFAULT false,
  p_can_view_audit_logs boolean DEFAULT false
)
RETURNS public.admin_permissions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.admin_permissions;
  v_super_admin_count integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'AUTH_REQUIRED';
  END IF;

  IF NOT public.has_admin_permission('manage_admins') THEN
    RAISE EXCEPTION 'MISSING_PERMISSION:manage_admins';
  END IF;

  IF p_profile_id IS NULL THEN
    RAISE EXCEPTION 'PROFILE_ID_REQUIRED';
  END IF;

  SELECT count(*)
  INTO v_super_admin_count
  FROM public.admin_permissions
  WHERE is_super_admin = true;

  IF v_super_admin_count = 1
     AND p_is_super_admin = false
     AND p_profile_id = auth.uid()
     AND public.is_super_admin() THEN
    RAISE EXCEPTION 'LAST_SUPER_ADMIN_PROTECTION';
  END IF;

  INSERT INTO public.admin_permissions (
    profile_id,
    is_super_admin,
    can_manage_orders,
    can_manage_wallets,
    can_manage_products,
    can_manage_settings,
    can_manage_maintenance,
    can_manage_admins,
    can_manage_coupons,
    can_manage_gift_cards,
    can_view_audit_logs,
    created_by,
    updated_by
  )
  VALUES (
    p_profile_id,
    p_is_super_admin,
    p_is_super_admin OR p_can_manage_orders,
    p_is_super_admin OR p_can_manage_wallets,
    p_is_super_admin OR p_can_manage_products,
    p_is_super_admin OR p_can_manage_settings,
    p_is_super_admin OR p_can_manage_maintenance,
    p_is_super_admin OR p_can_manage_admins,
    p_is_super_admin OR p_can_manage_coupons,
    p_is_super_admin OR p_can_manage_gift_cards,
    p_is_super_admin OR p_can_view_audit_logs,
    auth.uid(),
    auth.uid()
  )
  ON CONFLICT (profile_id) DO UPDATE
  SET is_super_admin = EXCLUDED.is_super_admin,
      can_manage_orders = EXCLUDED.can_manage_orders,
      can_manage_wallets = EXCLUDED.can_manage_wallets,
      can_manage_products = EXCLUDED.can_manage_products,
      can_manage_settings = EXCLUDED.can_manage_settings,
      can_manage_maintenance = EXCLUDED.can_manage_maintenance,
      can_manage_admins = EXCLUDED.can_manage_admins,
      can_manage_coupons = EXCLUDED.can_manage_coupons,
      can_manage_gift_cards = EXCLUDED.can_manage_gift_cards,
      can_view_audit_logs = EXCLUDED.can_view_audit_logs,
      updated_by = auth.uid()
  RETURNING * INTO v_row;

  PERFORM public.append_admin_audit_log(
    'upsert_admin_permissions',
    'admin_permissions',
    p_profile_id::text,
    jsonb_build_object(
      'is_super_admin', v_row.is_super_admin,
      'can_manage_orders', v_row.can_manage_orders,
      'can_manage_wallets', v_row.can_manage_wallets,
      'can_manage_products', v_row.can_manage_products,
      'can_manage_settings', v_row.can_manage_settings,
      'can_manage_maintenance', v_row.can_manage_maintenance,
      'can_manage_admins', v_row.can_manage_admins,
      'can_manage_coupons', v_row.can_manage_coupons,
      'can_manage_gift_cards', v_row.can_manage_gift_cards,
      'can_view_audit_logs', v_row.can_view_audit_logs
    )
  );

  RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.bootstrap_super_admin()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_existing_super_admin uuid;
  v_status text := 'bootstrapped';
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'AUTH_REQUIRED';
  END IF;

  -- يمنع أي مستخدم عادي من الاستحواذ على أول Super Admin
  IF NOT EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = v_user_id
      AND p.role = 'admin'
  ) THEN
    RAISE EXCEPTION 'BOOTSTRAP_REQUIRES_LEGACY_ADMIN_ROLE';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext('raiz3y_store_super_admin_bootstrap'));

  SELECT ap.profile_id
  INTO v_existing_super_admin
  FROM public.admin_permissions ap
  WHERE ap.is_super_admin = true
  LIMIT 1;

  IF v_existing_super_admin IS NOT NULL AND v_existing_super_admin <> v_user_id THEN
    RAISE EXCEPTION 'SUPER_ADMIN_ALREADY_EXISTS';
  END IF;

  IF v_existing_super_admin = v_user_id THEN
    v_status := 'already_super_admin';
  END IF;

  INSERT INTO public.admin_permissions (
    profile_id,
    is_super_admin,
    can_manage_orders,
    can_manage_wallets,
    can_manage_products,
    can_manage_settings,
    can_manage_maintenance,
    can_manage_admins,
    can_manage_coupons,
    can_manage_gift_cards,
    can_view_audit_logs,
    created_by,
    updated_by
  )
  VALUES (
    v_user_id,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    v_user_id,
    v_user_id
  )
  ON CONFLICT (profile_id) DO UPDATE
  SET is_super_admin = true,
      can_manage_orders = true,
      can_manage_wallets = true,
      can_manage_products = true,
      can_manage_settings = true,
      can_manage_maintenance = true,
      can_manage_admins = true,
      can_manage_coupons = true,
      can_manage_gift_cards = true,
      can_view_audit_logs = true,
      updated_by = v_user_id;

  PERFORM public.append_admin_audit_log(
    'bootstrap_super_admin',
    'admin_permissions',
    v_user_id::text,
    jsonb_build_object('profile_id', v_user_id, 'bootstrap', true)
  );

  RETURN jsonb_build_object(
    'status', v_status,
    'profile_id', v_user_id,
    'is_super_admin', true
  );
END;
$$;

-- -----------------------------------------------------------------------------
-- RLS + Grants
-- -----------------------------------------------------------------------------
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "store_settings_public_read" ON public.store_settings;
CREATE POLICY "store_settings_public_read"
ON public.store_settings
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "admin_permissions_self_read" ON public.admin_permissions;
CREATE POLICY "admin_permissions_self_read"
ON public.admin_permissions
FOR SELECT
USING (profile_id = auth.uid());

DROP POLICY IF EXISTS "admin_permissions_super_admin_read" ON public.admin_permissions;
CREATE POLICY "admin_permissions_super_admin_read"
ON public.admin_permissions
FOR SELECT
USING (public.is_super_admin());

DROP POLICY IF EXISTS "admin_audit_logs_self_or_privileged_read" ON public.admin_audit_logs;
CREATE POLICY "admin_audit_logs_self_or_privileged_read"
ON public.admin_audit_logs
FOR SELECT
USING (
  admin_id = auth.uid()
  OR public.is_super_admin()
  OR public.has_admin_permission('view_audit_logs')
);

REVOKE ALL ON public.store_settings FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.admin_permissions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.admin_audit_logs FROM PUBLIC, anon, authenticated;

GRANT SELECT ON public.store_settings TO anon, authenticated;
GRANT SELECT ON public.admin_permissions TO authenticated;
GRANT SELECT ON public.admin_audit_logs TO authenticated;

GRANT EXECUTE ON FUNCTION public.is_admin() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_super_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_admin_permission(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_admin_context() TO authenticated;
GRANT EXECUTE ON FUNCTION public.append_admin_audit_log(text, text, text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_store_exchange_rate(numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_store_maintenance(boolean, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.upsert_admin_permissions(
  uuid,
  boolean,
  boolean,
  boolean,
  boolean,
  boolean,
  boolean,
  boolean,
  boolean,
  boolean,
  boolean
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.bootstrap_super_admin() TO authenticated;

-- -----------------------------------------------------------------------------
-- Realtime لوضع الصيانة في الواجهة الرئيسية
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'store_settings'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.store_settings;
  END IF;
EXCEPTION
  WHEN undefined_object THEN
    NULL;
END;
$$;

COMMIT;
