#!/usr/bin/env node
/**
 * RAIZEY STORE — icon sprite builder.
 *
 * Single icon system: Lucide (stroke icons) + Simple Icons (brand marks, CC0).
 * Legacy Font Awesome class names are mapped in assets/icons/fa-to-lucide.json.
 *
 * Usage:
 *   node scripts/build_icons.mjs          # download (cached) + write the sprite
 *   node scripts/build_icons.mjs --check  # validate only, never touches the network
 */
import fs from "node:fs";
import path from "node:path";
import { ROOT, SPRITE_PATH, LUCIDE_VERSION, SIMPLE_ICONS_VERSION, SYSTEM_ICONS, readMap, collectLegacyIcons, collectSpriteRefs, collectLucideAttrs } from "./lib_icons.mjs";

const CHECK_ONLY = process.argv.includes("--check");
const CACHE = path.join(ROOT, ".cache/icons");
const LUCIDE_CDN = (n) => `https://unpkg.com/lucide-static@${LUCIDE_VERSION}/icons/${n}.svg`;
const BRAND_CDN = (n) => `https://unpkg.com/simple-icons@${SIMPLE_ICONS_VERSION}/icons/${n}.svg`;

const map = readMap();

// ── 1. What does the app actually need? ─────────────────────────────────────
const legacy = collectLegacyIcons();
const unmapped = [...legacy.keys()].filter((k) => !(k in map.icons) && !(k in map.brands));
if (unmapped.length) {
  console.error("✖ Unmapped legacy icon classes (add them to assets/icons/fa-to-lucide.json):");
  unmapped.forEach((n) => console.error(`   - ${n}  (used in: ${[...new Set(legacy.get(n))].join(", ")})`));
  process.exit(1);
}

const needed = new Set([...collectSpriteRefs(), ...collectLucideAttrs(), ...SYSTEM_ICONS]);
for (const fa of legacy.keys()) needed.add(map.icons[fa] ?? map.brands[fa]);

const brandNames = new Set(Object.values(map.brands));
console.log(`ℹ ${legacy.size} legacy icon classes · ${needed.size} unique icons needed`);

// ── 2. Existing sprite symbols (offline check path) ─────────────────────────
const existing = fs.existsSync(SPRITE_PATH) ? fs.readFileSync(SPRITE_PATH, "utf8") : "";
const existingIds = new Set([...existing.matchAll(/<symbol id="i-([a-z0-9-]+)"/g)].map((m) => m[1]));

if (CHECK_ONLY) {
  const missing = [...needed].filter((n) => !existingIds.has(n));
  if (missing.length) {
    console.error(`✖ sprite is missing ${missing.length} icon(s): ${missing.join(", ")}`);
    console.error("  Run: node scripts/build_icons.mjs");
    process.exit(1);
  }
  console.log(`✔ sprite check passed — ${existingIds.size} symbols, ${needed.size} used, 0 missing`);
  process.exit(0);
}

// ── 3. Fetch sources (cache-first so rebuilds are offline-friendly) ─────────
fs.mkdirSync(CACHE, { recursive: true });

async function fetchIcon(name, isBrand) {
  const cacheFile = path.join(CACHE, `${isBrand ? "brand-" : ""}${name}.svg`);
  if (fs.existsSync(cacheFile)) return fs.readFileSync(cacheFile, "utf8");
  const url = isBrand ? BRAND_CDN(name) : LUCIDE_CDN(name);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`cannot download ${url} → HTTP ${res.status}`);
  const svg = await res.text();
  fs.writeFileSync(cacheFile, svg);
  return svg;
}

function innerOf(svg) {
  return svg
    .replace(/^[\s\S]*?<svg\b[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .replace(/\s+/g, " ")
    .trim();
}

const symbols = [];
for (const name of [...needed].sort()) {
  const isBrand = brandNames.has(name);
  const svg = await fetchIcon(name, isBrand);
  const body = innerOf(svg);
  if (!body) {
    console.error(`✖ empty icon body for "${name}"`);
    process.exit(1);
  }
  const attrs = isBrand
    ? 'viewBox="0 0 24 24" fill="currentColor" stroke="none"'
    : 'viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';
  symbols.push(`  <symbol id="i-${name}" ${attrs}>${body}</symbol>`);
}

const header = `<!-- RAIZEY STORE icon sprite — generated by scripts/build_icons.mjs. Do not edit by hand.
     Lucide v${LUCIDE_VERSION} (ISC) · Simple Icons v${SIMPLE_ICONS_VERSION} (CC0) for brand marks.
     ${symbols.length} symbols · usage: <svg class="rz-i" aria-hidden="true"><use href="assets/icons/lucide-sprite.svg#i-check"></use></svg> -->
`;
const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true" focusable="false">\n${header}${symbols.join("\n")}\n</svg>\n`;
fs.writeFileSync(SPRITE_PATH, sprite);
console.log(`✔ wrote ${path.relative(ROOT, SPRITE_PATH)} — ${symbols.length} symbols, ${(sprite.length / 1024).toFixed(1)} KB`);
